/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu;

import bank.account.Account;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Nhlamulo_M
 */
public class Withdraw extends javax.swing.JFrame {

    /**
     * Creates new form Withdraw
     */
    private ArrayList<String> userData;
    private String username = "";
    private String password = "";
    
    public Withdraw() {
        initComponents();
        userData = new ArrayList<>();
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
        public String toString(String[] array){
        
        String data = "";
        
        for(int x = 0; x < array.length; x++){
            
            if(data.equals("")){
                
                data = array[x];
            }
            else{
                
                data += "," +  array[x];
            }
        }
        
        return data;
    }
        public void writeTransaction(String transaction,double amount){
        
        //instance object of the decimal format class
        DecimalFormat dc = new DecimalFormat("R###,###.00");
        
        //instatiating the file object
        File myFile = new File("src/datafiles/statements.txt");
        
        
        try{
            
            FileWriter write = new FileWriter(myFile,true);
            BufferedWriter writeData = new BufferedWriter(write);
            
            LocalDate date = LocalDate.now();
            
            String sign = "";
            
            if(transaction.equalsIgnoreCase("deposit")){
                
                sign = "+";
            }
            else{
                
                sign = "-";
            }
            
            String statement  = "";
             statement = date  + "\t  " + transaction + "\t  " + sign + "   " +
                    dc.format(amount);
            
            writeData.write(statement);
            writeData.newLine();
            writeData.close();
                        
        }
        catch(IOException e){
            
            System.out.println(e.getMessage());
        }
                
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("WITHDRAW AMOUNT");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("WITHDRAW AMOUNT");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("WITHDRAW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(125, 125, 125))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(jButton1)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //read file data
        File myFile = new File("src/datafiles/Bankaccounts.txt");
        String[] array;
        
        try{
            
            FileReader read = new FileReader(myFile);
            BufferedReader readFile = new BufferedReader(read);
            
            String data = readFile.readLine();
            
            while(data != null){
                
                String[] info = data.split(",");
                
                if(username.equals(info[0]) && 
                   password.equals(info[1])){
                    
                    if(Double.parseDouble(jTextField1.getText()) <= 
                            Double.parseDouble(info[5])){
                        
                        double amount = Double.parseDouble(jTextField1.getText());
                        
                        info[5] = String.valueOf(Double.parseDouble(info[5]) - amount);
                        
                        //adding the data inside the arraylist
                        userData.add(toString(info));
                        JOptionPane.showMessageDialog(null, "Withdraw successful!");
                        writeTransaction("withdraw", amount);
                                
                    }
                    else{
                        
                        JOptionPane.showMessageDialog(null, "Insufficient amount!");
                    }
                }
                else{
                    
                    userData.add(data);
                }
                
                data = readFile.readLine();
            }
        }
        catch(IOException e){
            
            System.out.println(e.getMessage());
        }
        
      
        
        /*try{
            
            FileWriter write = new FileWriter(myFile);
            BufferedWriter writeFile  = new BufferedWriter(write);
            
            writeFile.write("");
            
        }
        catch(IOException e){
            
            System.out.println("File not found!");
        }*/
        
        try{
            
            FileWriter write = new FileWriter(myFile);
            BufferedWriter writeFile  = new BufferedWriter(write);
            
            for(String data:userData){
                
                writeFile.write(data);
                writeFile.newLine();
            }
           
            writeFile.close();
        }
        catch(IOException e){
            
            System.out.println("file not found!");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Withdraw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
